const { spawn } = require('child_process');
const fs = require('fs');
const path = require('path');
const http = require('http');

let serverProcess = null;
const envJsPath = path.resolve(__dirname, '../../frontend/js/env.js');
let originalEnvContent = null;

// Starts the backend server on a specific test port (default 5001)
function startTestServer(port = 5001) {
  return new Promise((resolve, reject) => {
    console.log(`[QA Helper] Starting backend test server on port ${port}...`);
    
    // Backup original env.js
    if (fs.existsSync(envJsPath)) {
      originalEnvContent = fs.readFileSync(envJsPath, 'utf8');
    }

    // Write temp env.js pointing to test server
    const tempEnvContent = `// Temporary env.js generated by QA test runner
window.env = {
  VITE_API_URL: "http://localhost:${port}/api",
  VITE_UPLOAD_URL: "http://localhost:${port}/uploads"
};
`;
    fs.writeFileSync(envJsPath, tempEnvContent);

    // Spawn server process
    const serverScript = path.resolve(__dirname, '../../backend/src/server.js');
    serverProcess = spawn('node', [serverScript], {
      cwd: path.resolve(__dirname, '../../backend'),
      env: {
        ...process.env,
        PORT: port,
        NODE_ENV: 'test',
        MONGODB_URI: process.env.MONGODB_URI || 'mongodb://localhost:27017/zazele-test'
      }
    });

    serverProcess.stdout.on('data', (data) => {
      const msg = data.toString();
      if (msg.includes('backend running on http://localhost')) {
        console.log(`[QA Helper] Backend test server responded active.`);
        resolve(serverProcess);
      }
    });

    serverProcess.stderr.on('data', (data) => {
      console.error(`[Backend Stderr] ${data.toString().trim()}`);
    });

    serverProcess.on('error', (err) => {
      console.error('[QA Helper] Failed to start backend server:', err);
      restoreEnvFile();
      reject(err);
    });

    // Fallback: Resolve if server takes too long but is likely up
    setTimeout(() => {
      resolve(serverProcess);
    }, 4000);
  });
}

// Check if a URL returns 200/ok
function pingUrl(url) {
  return new Promise((resolve) => {
    http.get(url, (res) => {
      resolve(res.statusCode === 200);
    }).on('error', () => {
      resolve(false);
    });
  });
}

// Stop the test server and restore original env.js configuration
function stopTestServer() {
  return new Promise((resolve) => {
    console.log('[QA Helper] Stopping backend test server...');
    restoreEnvFile();

    if (serverProcess) {
      serverProcess.kill('SIGTERM');
      // Wait briefly for server process to die
      setTimeout(() => {
        serverProcess = null;
        resolve();
      }, 1000);
    } else {
      resolve();
    }
  });
}

function restoreEnvFile() {
  if (originalEnvContent !== null) {
    fs.writeFileSync(envJsPath, originalEnvContent);
    originalEnvContent = null;
    console.log('[QA Helper] Restored original env.js');
  }
}

module.exports = {
  startTestServer,
  stopTestServer,
  pingUrl
};
